name: Github Action for LaTeX
author: Tom Cornebize
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.compilation-target }}
inputs:
  compilation-target:  # id of input
    description: 'What to compile'
    required: false
    default: 'all'
