on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Compilation of the thesis
    steps:
    - name: Set up the repository
      uses: actions/checkout@v2
    - name: Compilation
      id: compilation
      uses: ./
      with:
          compilation-target: thesis.pdf
    - name: File informations
      run: |
          echo "Number of pages : ${{ steps.compilation.outputs.nb_pages }}"
          echo "File size       : ${{ steps.compilation.outputs.file_size }}"
          test -f thesis_data.csv || echo "timestamp,nb_pages,file_size" > thesis_data.csv
          echo "$(date '+%Y-%m-%d %H:%M:%S'),${{ steps.compilation.outputs.nb_pages }},${{ steps.compilation.outputs.file_size }}" >> thesis_data.csv
          cat thesis_data.csv
    - name: Upload the resulting PDF
      uses: actions/upload-artifact@v2
      with:
        path: thesis.pdf
