on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Compilation of the thesis
    steps:
    - name: Set up the repository
      uses: actions/checkout@v2
    - name: Compilation
      uses: ./
    - name: Upload the resulting PDF
      uses: actions/upload-artifact@v2
      with:
        path: thesis.pdf
